%YAML:1.0
#############################################
#   Mapping                                 #
#############################################
# The points [out of local map] is considered to be [OUT_OF_MAP]
# The points [out of virtual ceil or ground] is considered to be [OCCUPIED]
fsm_node:
  rog_map:
    map_sliding:
      enable: false
      # The minimum distance [m] to slide the map.
      threshold: 0.01

    # If the map rolling is disable, the map origin [m] should be set.
    fix_map_origin: [0, 0, 0]

    frontier_extraction_en: false

    resolution: 0.1
    inflation_en: false
    inflation_resolution: 0.3
    inflation_step: 1
    map_size: [25, 25, 25]

    # Virtual ceil and ground
    virtual_ceil_height: 9999
    virtual_ground_height: -9999

    # Intensity filter for input point cloud. If the point intensity is less than this value,
    # it will be ignored (to avoid noise like dusk).
    intensity_thresh: -1
    # The temporal downsample rate for input point cloud.
    #  e.g. if set to k, the point cloud will be downsampled to 1/k.
    point_filt_num: 1

    # Probabilistc update
    raycasting:
      # if disable, the map will only maintain occupied information, and all other grid
      # will be considered as unknown.
      enable: true
      batch_update_size: 3
      local_update_box: !!opencv-matrix
        rows: 1
        cols: 3
        dt: d
        data: [30, 30, 30]
      # The range of raycasting [m].
      ray_range:  !!opencv-matrix
        rows: 1
        cols: 2
        dt: d
        data: [0.0, 40]

      # logit: log((x)/(1-(x)))
      p_min: 0.12
      p_miss: 0.49
      p_free: 0.499
      p_occ: 0.6 # we set it to 0.6 to make the map more conservative
      p_hit: 0.9
      p_max: 0.98
      # The threshold of a non-occupied inf map grid to be considered as free. [0.0-1.0]
      # for counter map, if each cell contains N cells in prob map, then only when
      # N_unk > N * unk_thresh cells are unknown, the cell will be considered as unknown.
      # example: 1) if unk_thresh is set 0.0, then once at least one cell in prob map is unknown,
      #             the cell will be considered as unknown.
      #         2) if unk_thresh is set to 1.0, then only all cells in prob map are unknown,
      #             the cell will be considered as unknown.
      # in all, 1.0 is more aggressive while 0.0 is more conservative.
      inf_map_known_free_thresh: 0.2

    gpu:
      GPU_BLOCKSIZE: 512
      CLOUD_BUFFER_SIZE: 100000

  astar:
    map_voxel_num: [50, 50, 20]
    visual_process: false
