#############################################
#   Mapping                                 #
#############################################
# The points [out of local map] is considered to be [OUT_OF_MAP]
# The points [out of virtual ceil or ground] is considered to be [OCCUPIED]
fsm_node:
  bag_name: "/home/amov/ws_nx/bags/2023-03-30-18-17-57-exploration-success.bag"
  rog_map:
    map_sliding:
      enable: true
      # The minimum distance [m] to slide the map.
      threshold: 0.01

    # If the map rolling is disable, the map origin [m] should be set.
    fix_map_origin: [ 0,0,0 ]

    frontier_extraction_en: false

    # If [enbale = true], the ROG-Map will actively take ros topic as input.
    #  else user should call function [updateMap] to update the map.h
    ros_callback:
      enable: true
      # cloud_topic: "/cloud_registered"
      # odom_topic: "/lidar_slam/odom"
      cloud_topic: "/velodyne_points"
      odom_topic: "/ground_truth/state"      
      odom_timeout: 20.0

    visulization:
      enbale: true
      # The rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
      time_rate: 10
      # The frame rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
      frame_rate: 0
      # visualization range along the odom [m].
      range: [ 8,8,8]
      frame_id: "world"
      pub_unknown_map_en: true

    resolution: 0.3
    inflation_resolution: 0.3
    inflation_step: 1
    map_size: [15,15,15]

    # Virtual ceil and ground
    virtual_ceil_height: 9999
    virtual_ground_height: -2


    # Intensity filter for input point cloud. If the point intensity is less than this value,
    # it will be ignored (to avoid noise like dusk).
    intensity_thresh: -1
    # The temporal downsample rate for input point cloud.
    #  e.g. if set to k, the point cloud will be downsampled to 1/k.
    point_filt_num: 1

    # Probabilistc update
    raycasting:
      # if disable, the map will only maintain occupied information, and all other grid
      # will be considered as unknown.
      enable: true
      batch_update_size: 3
      local_update_box: [30,30,30]
      # The range of raycasting [m].
      ray_range: [0.5, 15]

      p_min: 0.12
      p_miss: 0.4
      p_free: 0.45
      p_occ: 0.55
      p_hit: 0.88
      p_max: 0.95
      # The threshold of a non-occupied inf map grid to be considered as free. [0.0-1.0]
      # which means for a gird contains [u] unknown grids and [f] known free grids.
      # if [f/(f+u) > inf_map_known_free_thresh], the grid will be considered as free.
      #  e.g. this thresh is set to 1.0, it measn a inf map grid is considered as free only if all grids in it are known free.
      inf_map_known_free_thresh: 0.2

    gpu:
      GPU_BLOCKSIZE: 128
      CLOUD_BUFFER_SIZE: 100000

  astar:
    map_voxel_num: [50,50,20]
    visual_process: false






